### ISSUE TITLE
iOS wallet app bug about contacts

### ISSUE THREAD

**Issue by RaceleaderQC** [helium/wallet-app#226] opened 2023-04-24 19:18 UTC
**Describe the bug**
Seems app only manage 2 contacts. When adding a 3rd one it completely erase the 2nd one and rewrites.

**To Reproduce**

1. Go to "contacts"
2. Click on "add contact"
3. Fill the form with 3rd contact infos
4. See error "erase second one"

**Expected behavior**
Should be able to add multiple contacts

**Screenshots**

https://user-images.githubusercontent.com/131708722/234094000-e1ae41a1-8237-44f2-aa43-fa8470bf9208.MOV

**Smartphone (please complete the following information):**

- Device: [iPhone13]
- OS: [iOS 16.3.1]
- App Version [2.0.5]

**Comment by jthiller** [comment] 2023-04-25 21:20
Duplicate of #209

**Closed by jthiller** 2023-04-25 21:20 UTC
Labels: bug
