### ISSUE TITLE
Switching between accounts doesn’t initially show correct balances, and often misses the decimal point for only HNT 

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#252] opened 2023-04-27 14:39 UTC
**Describe the bug**

When changing between accounts, the value for HNT initially doesn't include a decimal place. As a result, a balance of 0.90, for example, will display as 90. The missing decimal is ephemeral, however, and will shortly correct to the proper value.

**To Reproduce**

1. Go to first account
2. Switch to second account
3. Switch back to first account
4. Observe HNT balance

**Expected behavior**
Correct value should be initially shown

**Screenshots**
<img width="531" alt="Screenshot 2023-04-27 at 10 36 13 AM" src="https://user-images.githubusercontent.com/37127765/234896617-cb3f0010-13cd-49dd-ad05-90f7dbbbcb0c.png">

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: 16.3
- App Version: 2.0.6

**Additional context**

**Comment by ChewingGlass** [comment] 2023-05-11 15:26
I'm not able to reproduce this, I think it must have been fixed with one of the other tickets.

**Closed by ChewingGlass** 2023-05-11 15:26 UTC
Labels: bug
