### ISSUE TITLE
After Ledger Nano X firmware upgrade, Helium Wallet v2 loses connection with device

### ISSUE THREAD

**Issue by ScoobyDoo24** [helium/wallet-app#139] opened 2023-03-22 01:36 UTC
**Describe the bug**

After upgrading Ledger firmware it had no apps installed, including Helium app.  After reinstalling Helium app on Ledger, Helium Wallet throws error when trying to send 1 HNT.  

**To Reproduce**

1. From Ledger Live on PC, follow prompts to upgrade firmware.
2. Reinstall Helium app using Ledger Live app on PC.
3. Put Helium Ledger app into ‘Waiting for commands’ mode.
4. Open Helium Wallet v2 and attempt to send 1 HNT from Ledger protected Helium wallet.
5. Helium Wallet app will advise to approve transaction on Ledger device, but no prompt appears on Ledger device.
6. After a few seconds, error appears as follows: “Ble Error: Device ####### Not Found”

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPad Pro
- OS: iPad OS 16.3.1
- App Version: Helium Wallet v2.0.0

**Additional context**

**Comment by jthiller** [comment] 2023-04-25 21:26
Duplicate of #195

**Closed by jthiller** 2023-04-25 21:26 UTC
Labels: bug
