### ISSUE TITLE
Importing an account breaks the app

### ISSUE THREAD

**Issue by matthewcarlreetz** [helium/wallet-app#465] opened 2023-09-15 20:46 UTC
This happens when importing an account. Restarting the app a few times fixes it.

<img width="414" alt="image" src="https://github.com/helium/wallet-app/assets/1760821/1cde0eec-4d83-4df9-aede-68474f237f98">

**Comment by ChewingGlass** [comment] 2023-09-17 15:58
This is due to a build issue on your local env, and not a bug in the app. Closing the issue

**Closed by ChewingGlass** 2023-09-17 15:58 UTC
Labels: bug
