### ISSUE TITLE
Support handling more than 10 word sets at once

### ISSUE THREAD

**Issue by illumina23** [helium/wallet-app#548] opened 2023-11-30 16:47 UTC
Helium Wallet 2.4.2 only lets me add 10 word sets at a time.  When I try to add the 11th it tells me "You have reached the wallet limit." and refuses to let me add more.

Why does this limit exist?  Can it be removed or increased?  I have more than 10 word sets and would rather not have to juggle them.

**Comment by ChewingGlass** [comment] 2023-12-19 21:07
@Perronef5 is there a reason this limit exists or can we just up it?

**Comment by ChewingGlass** [comment] 2024-03-12 20:26
Duplicate of https://github.com/helium/wallet-app/issues/541

**Closed by ChewingGlass** 2024-03-12 20:26 UTC

**Comment by illumina23** [comment] 2024-03-12 23:22
Can you link to the commit where this was completed?

**Comment by ChewingGlass** [comment] 2024-03-13 18:38
https://github.com/helium/wallet-app/pull/685
